AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Event Registration System with AI-Powered Networking.

# Global settings for all functions
Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        EVENTS_TABLE: Events
        REGISTRATIONS_TABLE: Registrations
        PROFILES_TABLE: MatchingProfiles

Resources:
  # -----------------------------------------------
  # API Gateway (The "Front Door")
  # -----------------------------------------------
  EventApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "https://d2eg0n1tt6gn3n.cloudfront.net"
        AllowHeaders:
          - Content-Type
        AllowMethods:
          - GET
          - POST
          - OPTIONS

  # -----------------------------------------------
  # DynamoDB Tables (The "Database")
  # -----------------------------------------------
  # Note: Tables already exist, so we comment them out to avoid AlreadyExists error
  # If you need to recreate them, delete the existing tables first using:
  # aws dynamodb delete-table --table-name Events
  # aws dynamodb delete-table --table-name Registrations
  # aws dynamodb delete-table --table-name MatchingProfiles
  
  # EventsTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Events
  #     BillingMode: PAY_PER_REQUEST
  #     AttributeDefinitions:
  #       - AttributeName: eventId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: eventId
  #         KeyType: HASH

  # RegistrationsTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Registrations
  #     BillingMode: PAY_PER_REQUEST
  #     AttributeDefinitions:
  #       - AttributeName: registrationId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: registrationId
  #         KeyType: HASH

  # MatchingProfilesTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: MatchingProfiles
  #     BillingMode: PAY_PER_REQUEST
  #     AttributeDefinitions:
  #       - AttributeName: userId
  #         AttributeType: S
  #       - AttributeName: eventId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: userId
  #         KeyType: HASH
  #       - AttributeName: eventId
  #         KeyType: RANGE
  #     GlobalSecondaryIndexes:
  #       - IndexName: eventId-index
  #         KeySchema:
  #           - AttributeName: eventId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
          
  # -----------------------------------------------
  # Lambda Functions (The "Engine")
  # -----------------------------------------------
  
  # --- Sujith's Functions ---
  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/registration/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Registrations
        - SESBulkTemplatedCrudPolicy: 
            IdentityName: "sriroop123@gmail.com"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /register
            Method: post
            ApiId: !Ref EventApi

  GetEventRecommendationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/recommendations/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: Events
        - DynamoDBReadPolicy:
            TableName: Registrations
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /recommendations
            Method: get
            ApiId: !Ref EventApi

  EventChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/chatbot/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: Events
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /chat
            Method: post
            ApiId: !Ref EventApi

  # --- Sriroop's Functions ---
  MatchMakerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/matchmaking/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: MatchingProfiles
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /find-matches
            Method: post
            ApiId: !Ref EventApi

  GetDashboardDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/dashboard/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: Events
        - DynamoDBReadPolicy:
            TableName: Registrations
        - DynamoDBReadPolicy:
            TableName: MatchingProfiles
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /dashboard
            Method: get
            ApiId: !Ref EventApi

  # --- Future Scope Function ---
  SendEventRemindersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/reminders/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: Registrations
        - SESBulkTemplatedCrudPolicy: 
            IdentityName: "sriroop123@gmail.com"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: "cron(0 9 * * ? *)"